### ISSUE TITLE
`could not touch` error

### ISSUE THREAD

**Issue by fazibear** [edib-tool/mix-edib#23]
After `mix edib` got something like this. Any ideas how to fix it ? 

Thanks for help.

```
| make[1]: Entering directory '/build'
| warning: mtime (modified time) for "/source/deps/moebius/.fetch" was set to the future, resetting to now
| ** (File.Error) could not touch "/source/deps/moebius/.fetch": read-only file system
|     (elixir) lib/file.ex:395: File.touch!/2
|     (mix) lib/mix/utils.ex:105: Mix.Utils.last_modified/1
|     (mix) lib/mix/utils.ex:83: anonymous fn/2 in Mix.Utils.stale_stream/2
|     (elixir) lib/stream.ex:396: anonymous fn/4 in Stream.filter/2
|     (elixir) lib/enum.ex:2843: Enumerable.List.reduce/3
|     (elixir) lib/stream.ex:1284: Enumerable.Stream.do_each/4
|     (elixir) lib/enum.ex:280: Enum.any?/2
|     (mix) lib/mix/dep/loader.ex:322: Mix.Dep.Loader.validate_app/1
```

**Comment by asaaki** [comment]
Not sure if still valid. If so, open an issue with reproducible steps.
