### ISSUE TITLE
EDIB failed after upgrading to Elixir 1.3

### ISSUE THREAD

**Issue by ferdinandchan** [edib-tool/mix-edib#9]
Hi, 

Thanks for creating this very useful tools. I was happy using it with Elixir 1.2.5, however, it stopped working after I upgrade to Elixir 1.3

Here is the error log.

```
fchan:gauge fchan$ mix edib
Will use EDIB tool v1.3.0
==> Packaging your app release into a docker image. Stay tuned!
| $> docker run --rm  -v "/Users/fchan/chaos/gauge:/source:ro" -v "/Users/fchan/chaos/gauge/tarballs:/stage/tarballs:rw"  edib/edib-tool:1.3.0
==> Creating artifact (might take a while) ...
| make -f edib/prerequisites.mk
| make[1]: Entering directory '/build'
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| rsync -av \
|   --exclude=.git\
|   --exclude=.edib.log \
|   --exclude=_build \
|   --exclude=deps \
|   --exclude=node_modules \
|   --exclude=rel/ \
|   --exclude=tarballs \
|   /source/ /build/app
| sending incremental file list
| created directory /build/app
| ./
| .gitignore
| README.md
| docker_build_and_release.sh
| gauge-template.sd.yml
| gauge.sd.yml
| mix.exs
| mix.lock
| config/
| config/config.exs
| config/dev.exs
| config/prod.exs
| config/prod.secret.exs
| config/test.exs
| data.nonode@nohost/
| lib/
| lib/gauge.ex
| lib/gauge/
| lib/gauge/endpoint.ex
| lib/gauge/plug_exometer.ex
| log.nonode@nohost/
| log/
| log/console.log
| log/crash.log
| log/error.log
| priv/
| priv/gettext/
| priv/gettext/errors.pot
| priv/gettext/en/
| priv/gettext/en/LC_MESSAGES/
| priv/gettext/en/LC_MESSAGES/errors.po
| priv/static/
| priv/static/favicon.ico
| priv/static/robots.txt
| priv/static/css/
| priv/static/css/app.css
| priv/static/css/app.css.map
| priv/static/images/
| priv/static/images/phoenix.png
| priv/static/js/
| priv/static/js/app.js
| priv/static/js/app.js.map
| test/
| test/test_helper.exs
| test/channels/
| test/controllers/
| test/controllers/health_check_controller_test.exs
| test/controllers/measure_controller_test.exs
| test/controllers/page_controller_test.exs
| test/support/
| test/support/channel_case.ex
| test/support/conn_case.ex
| test/views/
| test/views/error_view_test.exs
| test/views/layout_view_test.exs
| test/views/page_view_test.exs
| web/
| web/gettext.ex
| web/router.ex
| web/web.ex
| web/channels/
| web/channels/user_socket.ex
| web/controllers/
| web/controllers/health_check_controller.ex
| web/controllers/measure_controller.ex
| web/controllers/page_controller.ex
| web/models/
| web/static/
| web/static/assets/
| web/static/assets/favicon.ico
| web/static/assets/robots.txt
| web/static/assets/images/
| web/static/assets/images/phoenix.png
| web/static/css/
| web/static/css/app.css
| web/static/js/
| web/static/js/app.js
| web/static/js/socket.js
| web/static/vendor/
| web/templates/
| web/templates/layout/
| web/templates/layout/app.html.eex
| web/templates/page/
| web/templates/page/index.html.eex
| web/views/
| web/views/error_helpers.ex
| web/views/error_view.ex
| web/views/layout_view.ex
| web/views/page_view.ex
| sent 611,603 bytes  received 1,261 bytes  1,225,728.00 bytes/sec
| total size is 606,980  speedup is 0.99
| if [ -d /root/ssh ]; then \
|   mkdir /root/.ssh && \
|   rsync -av --no-owner /root/ssh/ /root/.ssh; \
| fi
| make[1]: Leaving directory '/build'
| make -f edib/edib.mk
| make[1]: Entering directory '/build'
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| make -f edib/check-exrm.mk
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| make[2]: Entering directory '/build'
| ** (CaseClauseError) no case clause matching: {:error, :tokens}
|     (kernel) file.erl:1368: :file.consult_stream/3
|     (kernel) file.erl:978: :file.consult/1
|     (mix) lib/mix/dep/elixir_scm.ex:20: Mix.Dep.ElixirSCM.read/1
|     (mix) lib/mix/tasks/loadpaths.ex:67: Mix.Tasks.Loadpaths.load_project/2
|     (mix) lib/mix/tasks/loadpaths.ex:30: Mix.Tasks.Loadpaths.run/1
|     (mix) lib/mix/tasks/app.start.ex:36: Mix.Tasks.App.Start.run/1
|     (mix) lib/mix/tasks/run.ex:63: Mix.Tasks.Run.run/1
|     (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
| edib/check-exrm.mk:12: *** The project as no 'exrm' dependency. Cannot proceed further.  Stop.
| make[2]: Leaving directory '/build'
| edib/edib.mk:28: recipe for target 'exrm' failed
| make[1]: *** [exrm] Error 2
| make[1]: Leaving directory '/build'
| edib/Makefile:6: recipe for target 'edib' failed
| make: *** [edib] Error 2
==> An error happened!
==> Reason: Artifact tarball not created! Check for any errors above.
fchan:gauge fchan$
```

Thanks

**Comment by asaaki** [comment]
Elixir 1.3 is only 3 days old, I had no time yet to update the whole toolchain. 😅

**Comment by ferdinandchan** [comment]
Thanks for the quick response. I'm still pretty new to Elixir + Phoenix + docker. If you can provide some rough guidelines, I can raise a PR and help :)

**Comment by asaaki** [comment]
Please use [mix-edib `v0.8.1`](https://github.com/edib-tool/mix-edib/releases/tag/v0.8.1) for Elixir 1.3 builds; this should address your issue and fix it for you.

**Comment by ferdinandchan** [comment]
Thanks @asaaki
